# Generated by Django 5.2.5 on 2025-08-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_title',
            field=models.CharField(max_length=200),
        ),
    ]
