# Generated by Django 5.2.5 on 2025-08-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
