# Generated by Django 5.2.5 on 2025-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
