# Generated by Django 5.2.5 on 2025-08-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_content',
            new_name='your_content',
        ),
    ]
