# Generated by Django 5.2.5 on 2025-08-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_rename_comment_content_comments_your_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='your_content',
            new_name='your_comment',
        ),
    ]
