# Generated by Django 5.2.5 on 2025-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_rename_your_content_comments_your_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-commented_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
